### ISSUE TITLE
Using install.sh to install Keras on the Game Servers

### ISSUE THREAD

**Issue by truell20** [HaliteChallenge/Halite#123]
@brianvanleeuwen is attempting to do this.

Here is his current install.sh:

```
pip3 install keras h5py theano -t ./rm -rf numpy*
mkdir /scratch/.theano
chmod -R 777 /scratch/.theano
```

Already done:
* Numpy doesn't seem to love local install over pip, so we added it to our sandbox
* Need --nodeps flag added to locally install libraries without locally installing numpy

Now we get this error log on the game servers:

```
--- Init ---
Using Theano backend.
 --- Bot used 251 milliseconds ---
-----------------------------------------------------------------------------
 --- Frame #1 ---
Traceback (most recent call last):
 --- Bot used 0 milliseconds ---
ERRORED!
Response received (if any):
Traceback (most recent call last):
 --- Bot was killed. Below is the rest of its output (if any): ---
  File "/home/ubuntu/Halite/worker/workingPath/1669/theano/configdefaults.py", line 1615, in filter_compiledir
    os.makedirs(path, 0o770)  # read-write-execute for user and group
  File "/usr/lib/python3.5/os.py", line 231, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/ubuntu/Halite/worker/workingPath/1669/.theano'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "MyBot.py", line 39, in 
configdefaults.py", line 1622, in filter_compiledir
    " '%s'. Check the permissions." % path)
    from keras.models import *
  File "/home/ubuntu/Halite/worker/workingPath/1669/keras/__init__.py", line 2, in 
    from . import backend
  File "/home/ubuntu/Halite/worker/workingPath/1669/keras/backend/__init__.py", line 66, in 
    from .theano_backend import *
  File "/home/ubuntu/Halite/worker/workingPath/1669/keras/backend/theano_backend.py", line 1, in 
    import theano
  File "/home/ubuntu/Halite/worker/workingPath/1669/theano/__init__.py", line 63, in 
    from theano.compile import (
  File "/home/ubuntu/Halite/worker/workingPath/1669/theano/compile/__init__.py", line 9, in 
    from theano.compile.function_module import *
  File "/home/ubuntu/Halite/worker/workingPath/1669/theano/compile/function_module.py", line 22, in 
    import theano.compile.mode
  File "/home/ubuntu/Halite/worker/workingPath/1669/theano/compile/mode.py", line 12, in 
    import theano.gof.vm
  File "/home/ubuntu/Halite/worker/workingPath/1669/theano/gof/vm.py", line 638, in 
    from . import lazylinker_c
  File "/home/ubuntu/Halite/worker/workingPath/1669/theano/gof/lazylinker_c.py", line 41, in 
    location = os.path.join(config.compiledir, 'lazylinker_ext')
  File "/home/ubuntu/Halite/worker/workingPath/1669/theano/configparser.py", line 324, in __get__
    self.__set__(cls, val_str)
  File "/home/ubuntu/Halite/worker/workingPath/1669/theano/configparser.py", line 335, in __set__
    self.val = self.filter(val)
  File "/home/ubuntu/Halite/worker/workingPath/1669/theano/
ValueError: Unable to create the compiledir directory '/home/ubuntu/Halite/worker/workingPath/1669/.theano/compiledir_Linux-3.13--generic-x86_64-with-Ubuntu-16.04-xenial-x86_64-3.5.2-64'. Check the permissions.

 --- End bot output ---
```

**Comment by truell20** [comment]
Final commit bbe7cbe808e1bd5235e14430b84e07540338706e
